# https://travis-ci.org/ryanss/python-holidays

language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - "pypy3-5.5.0"  # 3.3
    - "pypy3-5.8.0"  # 3.5

env:
    - DATEUTIL=python-dateutil==2.2
    - DATEUTIL=python-dateutil

install:
    - pip install $DATEUTIL
    - python setup.py install
    - pip install "flake8==2.6.2; python_version == '2.6'"
    - pip install "flake8; python_version > '2.6'"
    - pip install coveralls

before_script:
    - flake8 holidays.py tests.py

script:
    - coverage run --omit=*site-packages*,*pypy* tests.py

after_success:
    - coveralls
