# https://travis-ci.org/dr-prodigy/python-holidays
dist: bionic
language: python
cache: pip

before_install:
  - pip install --upgrade pip

install:
# hijri-converter not available < python 3.6
  - if [[
      $TRAVIS_PYTHON_VERSION == '3.9' ||
      $TRAVIS_PYTHON_VERSION == '3.8' ||
      $TRAVIS_PYTHON_VERSION == '3.7' ||
      $TRAVIS_PYTHON_VERSION == '3.6' ||
      $TRAVIS_PYTHON_VERSION == 'pypy3'
    ]]; then pip install hijri-converter; fi
  - pip install python-dateutil
  - pip install convertdate
  - pip install six
  - pip install flake8
  - pip install coveralls
  - python setup.py install

matrix:
  include:
#    - python: '3.9'
    - python: '3.8'
    - python: '3.7'
    - python: '3.6'
    - python: '3.5'
    - python: '2.7'
    - python: 'pypy3'

before_script:
    - flake8 --ignore=F401,W504 constants.py holiday_base.py utils.py holidays/countries/*.py

script:
    - coverage run --omit=*site-packages*,*pypy* tests.py

after_success:
    - coveralls
